name: Build Java Android Application
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Download Gradle Wrapper
        run: wget https://services.gradle.org/distributions/gradle-8.1.0-bin.zip -O gradle.zip && unzip -q gradle.zip
      - name: Create APK
        run: ./gradle-8.1.0/bin/gradle assembleRelease