name: Build Java Android Application
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
	  distribution: 'zulu'
          java-version: '17'
      - name: Build application
        run: mvn clean install
      - name: Create APK
        run: ./gradlew assembleRelease